export const statesMap = new Map([
    ['Andhra Pradesh', '01'],
    ['Arunachal Pradesh', '02'],
    ['Assam', '03'],
    ['Bihar', '04'],
    ['Chhattisgarh', '05'],
    ['Goa', '06'],
    ['Gujarat', '07'],
    ['Haryana', '08'],
    ['Himachal Pradesh', '09'],
    ['Jammu & Kashmir', '10'],
    ['Jharkhand', '11'],
    ['Karnataka', '12'],
    ['Kerala', '13'],
    ['Madhya Pradesh', '14'],
    ['Maharashtra', '15'],
    ['Manipur', '16'],
    ['Meghalaya', '17'],
    ['Mizoram', '18'],
    ['Nagaland', '19'],
    ['Odisha', '20'],
    ['Punjab', '21'],
    ['Rajasthan', '22'],
    ['Sikkim', '23'],
    ['TamilNadu', '24'],
    ['Telangana', '25'],
    ['Tripura', '26'],
    ['Uttar Pradesh', '27'],
    ['Uttarakhand', '28'],
    ['West Bengal', '29'],
    ['Delhi', '30'],
    ['Andaman & Nicobar', '31'],
    ['Chandigarh', '32'],
    ['Dadra & Nagar Haveli', '33'],
    ['Daman & Diu', '34'],
    ['Lakshadweep', '35'],
    ['Puducherry', '36']
  ]);
  